let squares = ["the tests are wrong.",
"i already tried that. didn't work.",
"never set up local env",
"my tests don't pass but my code is right",
"didn't save before running tests",
"that didn't work *changes all code back*",
"asks for project help",
"sneakily asks for project help",
"hi. ss please",
"i don't know",
"wont send code or errors",
"didn't read the README",
"didn't read error",
"okay *immediately sends next error*",
"didn't fork lab",
"cloned flatiron version of lab",
"my tests aren't working",
"didn't migrate",
"pokemon teams",
"pig latinizer",
"hello world lab",
"hashketball",
"prime?",
"code in spec file",
"writing code in terminal",
"use code snippet please",
"bundler issue",
"didn't bundle install",
"hasn't written any code",
"pastes every lab test",
"unresponsive",
"uh oh ubuntu",
"submit light won't turn green",
"no ssh key",
"Adam gives karma",
"zombie server",
"changed spec files",
"can we zoom",
"student sends their own zoom link",
"Helen",
"npm headache",
"omniauth",
"student has 100 tabs open",
"expertchat ---",
"no active room",
"malcome gif"];

export default squares;